version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: video_production_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: video_production_manager
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - video_production_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video_production_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/video_production_manager?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_change_this_in_production
    depends_on:
      - mongodb
    networks:
      - video_production_network
    volumes:
      - ./uploads:/app/uploads

  nginx:
    image: nginx:alpine
    container_name: video_production_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - video_production_network

volumes:
  mongodb_data:

networks:
  video_production_network:
    driver: bridge